### ISSUE TITLE
console output not working

### ISSUE THREAD

**Issue by ivan-modelical** [cwapi3d/PythonConsole#1]
Hi  @jspaquet ,

please keep on the great work of opening CADWORK API!!

We are using the console and have found a couple of odd things we'd love you to look into:

1. We cannot print to console:
```
>>> print('Hello World')
ERROR:
'NoneType' object has no attribute 'write'
>>> print("Hello World")
ERROR:
'NoneType' object has no attribute 'write'
>>> 
```
2. Up cursor does not bring you back last command
3. One cannot input multiline code snippets unless created on another editor and pasted in the console window

**Comment by jspaquet** [comment]
For 1 we also noticed the issue on our end. We have a plan to fix this but no timeline at this time.

Can you create separate issues for 2 and 3? It is much easier to keep track of issues individually.

**Comment by jspaquet** [comment]
Issue fixed starting with tomorrow's builds (V27+).
