### ISSUE TITLE
multiline statements

### ISSUE THREAD

**Issue by fbpyr** [cwapi3d/PythonConsole#2]
Thank you so much for a Python REPL in cadwork! 
In Rhino and Revit I happily use RevitPythonShell 
and RhinoPythonShell a lot! 🙂 

Unfortunately a few pretty important features are missing:
up-arrow-repeat and print statements as shown in #1 
and multiline statements: 

```
>>> for i in [1,2,3]:
ERROR:
unexpected EOF while parsing (<string>, line 2)
>>> 
```

While it is technically possible to write many things as 
one-liner, readbility and usability would suffer.

Are there plans to extend Cadwork PythonConsole further?
Thank you.

**Comment by jspaquet** [comment]
This is a known issue. We are working on a fix but I can't give a timeline as of now.

We do have plans to extend the PythonConsole project to get it comparable to IDLE, but keep in mind PythonConsole was just a toy we developed in Montreal to help debug things. We never really anticipated usage outside of the company. We've had a lot more interest than we thought so we do have plans to extend it as mentioned previously.

**Comment by fbpyr** [comment]
Hi @jspaquet, thank you for your answer! 

I see, no problem. 
I was anyways not expecting any timeline info, 
just wanted to know - as sometimes repos go dormant - 
whether the plan is to continue - which seems it is. 🙂 

Well, maybe it could even be possible to strive for something 
better than the standard IDLE? 
Maybe (?) it would be possible to build on the work of 
something like 
* bpython https://bpython-interpreter.org/  or 
* ptpython https://github.com/prompt-toolkit/ptpython

They are both far better than idle, offering 
multiline repeat/edit, autocompletion&autosuggestion, 
syntax highlighting theme choices, doc strings and more.
Ptpython seems to be easier to get running on win10 
machines, so as a quick experiment I embedded 
ptpython into a cadwork Python script:

![image](https://user-images.githubusercontent.com/73931454/112591694-07b1b700-8e05-11eb-8365-e19e6c786ff3.png)


^^ Which works very nicely, *but unfortunately it only 
runs once*. 🤔 
After quitting ptpython, cadwork still works, 
but if I rerun the script to get a second ptpython console,
cadwork unfortunately crashes.

**Comment by ivan-modelical** [comment]
Thanks @jspaquet 

It's very good news that you are planning to keep on developing the python console. Having quick feedback on what we do makes developing so much easy. Keep up the good work!

**Comment by jspaquet** [comment]
Issue fixed starting with tomorrow's builds (V27+).

**Comment by fbpyr** [comment]
Just wanted to quickly add, that in cadwork v28 the above way of bringing ptpython repl into cadwork console 
as commented above and as shown in https://gist.github.com/fbpyr/ad9dd650212ca60b7d00d283755ee58a
does not crash anymore. 🙂
